name: Run Docker – Ubuntu
################################################################################
# TRIGGERS
################################################################################
on:
  # 1) build automatically when *any* Dockerfile is pushed to main
  push:
    branches: [ main ]
    paths:    [ '**/*Dockerfile' ]

  # 2) build automatically at 00:00 UTC on the 1-st of every month
  schedule:
    - cron: '0 0 1 * *'

  # 3) manual run
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Folder the script should cd into'
        type: string
        default: 'containers/ubuntu'

      build_context:
        description: 'Docker build context'
        type: string
        default: 'github_workspace'      # token → repo root

      docker_file_name:
        description: 'Path to the Dockerfile (relative to build-context)'
        type: string
        default: 'containers/ubuntu/Dockerfile'   # <── key change

      docker_image_name:
        description: 'Image name (repo/name)'
        type: string
        default: 'ubuntu-base-docker-container/ubuntu-base'

      registry_url:
        description: 'Container registry URL'
        type: string
        default: 'ghcr.io'

      enable_debug_mode:
        description: 'Pass -DebugMode to the script'
        type: boolean
        default: false

      push_docker_image:
        description: 'Push image after build?  (true/false string)'
        type: string
        default: 'true'

################################################################################
# JOBS
################################################################################
jobs:
  run-script:
    name: Build & (optionally) push image
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: pwsh

    ########################
    # 1.  Resolve inputs   #
    ########################
    env:
      IN_WD:     ${{ github.event.inputs.working_directory  || 'containers/ubuntu' }}
      IN_CTX:    ${{ github.event.inputs.build_context      || 'github_workspace'   }}
      IN_DF:     ${{ github.event.inputs.docker_file_name   || 'containers/ubuntu/Dockerfile' }}
      IN_IMG:    ${{ github.event.inputs.docker_image_name  || 'ubuntu-base-docker-container/ubuntu-base' }}
      IN_REG:    ${{ github.event.inputs.registry_url       || 'ghcr.io' }}
      IN_DBG:    ${{ github.event.inputs.enable_debug_mode  || 'false' }}
      IN_PUSH:   ${{ github.event.inputs.push_docker_image  || 'true'  }}

    ########################
    # 2.  Steps            #
    ########################
    steps:
      - uses: actions/checkout@v3

      - name: Build (and optionally push)
        run: |
          # --------------------------------------------------------------
          # Absolute path to repository root
          # --------------------------------------------------------------
          $repoRoot = '${{ github.workspace }}'

          # --------------------------------------------------------------
          # workingDir  : directory we cd into
          # contextPath : build context passed to docker build
          # --------------------------------------------------------------
          $workingDir  = if ($Env:IN_WD  -eq 'github_workspace') { $repoRoot } else { Join-Path $repoRoot $Env:IN_WD  }
          $contextPath = if ($Env:IN_CTX -eq 'github_workspace') { $repoRoot } else { Join-Path $repoRoot $Env:IN_CTX }

          ./Run-Docker.ps1 `
            -WorkingDirectory $workingDir `
            -BuildContext     $contextPath `
            -DockerFileName   $Env:IN_DF `
            -DockerImageName  $Env:IN_IMG `
            -RegistryUrl      $Env:IN_REG `
            -RegistryUsername '${{ secrets.RegistryUsername }}' `
            -RegistryPassword '${{ secrets.RegistryPassword }}' `
            -ImageOrg         '${{ github.repository_owner }}' `
            -PushDockerImage  $Env:IN_PUSH `
            -DebugMode        $Env:IN_DBG
